### ISSUE TITLE
Changes from the DeepNestPort

### ISSUE THREAD

**Issue by petrasvestartas** [9swampy/DeepNestSharp#11]
Hi,

I have been using and the original DeepNestPort for more than three years. It worked well for me. But I gradually see that this repository is not updated anymore, while yours stays "alive". I always try to think how it can be improved.

I would like to ask question not about interface but about the main library itself.

What did you improve in comparison to the DeepNestPort?
It would be great to hear indepth insights since the library is quite large.

**Comment by 9swampy** [comment]
**"If I have seen further, it is by standing upon the shoulders of giants"**<br />
Jack and Felix have done some great work but the Original's use of a remote service
to translate between image formats was an issue and the Port just wasn't proving flexible/stable 
enough for my needs. 

Felix was keen to keep true to the original DeepNest code in DeepNestPort...
> > [Hope you consider breaking away from the legacy code base because it's getting really hard to merge.](https://github.com/fel88/DeepNestPort/issues/12#issuecomment-875273391)
> 
> I'll try, but it is important to keep compatibility with the original code...
> I think we shouldn't entangle our repositories too much

...so DeepNestSharp was born. It:
1. completely rebuilds the UI using WPF on Net.Core (currently 6)
2. is a huge refactor which has paid some dividends
- Readability/Maintainability of the code
- UnitTest coverage
- Many crash causing bugs fixed
- Eliminate need for the C++ Minkowski
- Deduplication of some pretty nasty/messy/unnecessary code: the Port as mentioned above tried to stay true to the original code as much as possible, and I found lots of issues were ported across from the original and even in some places issues were exacerbated 
- Eliminate overlapping parts (though that has come with a bit of a performance hit)
- Merge-line functionality reimplemented (was in Jack's original but never made it in to the original Port)
- Improved configuration documentation and more things exposed
- Edit, Load and Save configuration
- Load and Save projects (*.dnest)
- Load and Save nest results (*.dnr)
- Edit, Load and Save sheet placements (*.dnsp)
- Load and Save SheetNfps (*.dnnfp) - useful for debugging
- Load and Save NfpCandidateLists (*.dnnfps) - useful for debugging
4. ...but also introduced some compromises and issues, some of which are outstanding... 
- The internal Minkowski implementation's less performant and goes wrong a little more often (but it's just a configuration switch to flip back if you need)
- Overall speed of iteration has degraded but the reliability of not crashing before finding the optimal nest improved (tortoise vs hare IMHO)
- The UI isn't great; I've struggled to get AvalonDock to work correctly/persist settings
- The refactor was intended to allow me to swap out the Genetic Algorithm for something more performant/off the shelf (and to facilitate plug-in replacement potentially from the community) - but I've just not got there _yet_
- Editing sheet placements is currently limited to moving & removing already placed parts; not yet possible to rotate or add parts, or move between sheets
- Cannot yet seed, restart or continue prior nest executions
5. ...and last but not least it's an active repo because I'm using it and have issues from time to time... If it works for you/helps you great; if you can contribute that'd be great too. There's fairly good test coverage but as Release 0.2.0 proved it's be no means complete... (0.2.1's been uploaded to fix the export issue already).

That's of the top of my head. YMMV :)

**Comment by petrasvestartas** [comment]
Thanks that is a long list.


I would like to clean up the code or see how I can use changes from your work, specially when you write:
* Deduplication of some pretty nasty/messy/unnecessary code: the Port as mentioned above tried to stay true to the original code as much as possible, and I found lots of issues were ported across from the original and even in some places issues were exacerbated
* Many crash causing bugs fixed
* Eliminate overlapping parts (though that has come with a bit of a performance hit)
* Per-part rotation restrictions; restrict a part to horizonal or vertical only orientation
* Merge-line functionality reimplemented (was in Jack's original but never made it in to the original Port)


If I understand correctly, it hardly possible to compare your code to the original port and merge fixed issues with the old repository? Is it correct?

**Comment by 9swampy** [comment]
If you were to step through specific bits of code as the nest is running you'd probably be able to follow each side by side; the overall ideas, processes and workflows remain pretty close to each other - but the refactor has really pulled things apart and separated concerns to make a lot more sense of the tangled web the code had become. Some refactors just made perfect sense, some were done so I could add test cases to try and tease the logic out of the dark rabbit holes that seemed to go on forever, and some made something opaque a little more easy to understand. Some didn't really help but didn't hurt either. Ultimately though the process is largely still the same.

Of course there's been upgrades and downright inappropriate things that are no more, some nomenclature that was just misleading that might still confuse and even be wrong. For instance;
- part and sheet polygons are referred to as NoFitPolygons throughout and that's just plain wrong but so pervasive it's proven hard to draw out
- NoFitPolygon.Rotation has two uses; 
1. to represent state and 
2. another to pass instruction to the nest - trying to split that dual purpose was the root of the issue that leaking in to the 0.2.0 release. There's loads of crazy like that still in there that I've been chipping away at.

I'll be honest and say I still struggle with the ClipperLib stuff and how it's being used; some of the test coverage that's in there will reveal that to anyone that goes under the hood; but any tests (documenting the assumptions that have been made in how the code works) are better than no tests while there's still so much in the code base that's undocumented and opaque. At least if tests get broken by code changes then it forces me to try to better understand bits that may have been misunderstood.

That said, from the list you highlighted of interest; both the **merge-line** and **overlapping part eliminations** would be pretty easy to retrofit back in to the old code base and you're ofc welcome to do so.

Ofc I'd welcome any input back this way too. There's no shortage of candidates begging for attention... refer for instance to the Help-Wanted tags I raised in the issue space...

If you have any feedback on how you've been able to use (or been prevented from using), or corrections to highlight/merge or just general feedback on usability I'd be all ears.
