### ISSUE TITLE
Spacing does not work

### ISSUE THREAD

**Issue by mnschoonmaker** [9swampy/DeepNestSharp#12]
Regardless of the SPACING and MERGELINES settings, vector edges are aligned/adjacent to one another without the SPACING, which logically would allow for a cnc router bit's cutting diameter.

**Comment by 9swampy** [comment]
Have to admit I'm a laser cutter... played around with the spacing to add to the tooltip explanations but haven't paid it much attention. 

That said I do know the MergeLine logic I put in would have 0 chance of working with a CNC kerf but spacing... could you attach your Project, preferably with loadable Parts; loads of them in the DxfFiles folde in the repo just to demonstrate what your setup is, what gets generated and how the output doesn't meet your expectations?

**Comment by mnschoonmaker** [comment]
Sure thing.

The ZIP file contains the dxfs in case you wanted them as well.

I really like what you’ve done so far but I use CNC for my work.

Thank you

Mike Schoonmaker
***@***.******@***.***>
cell: 734.604.0999

**Comment by 9swampy** [comment]
Not sure where the zip went; any chance you could commit to a fork of the repo and I'll pick it up and take a look?

**Comment by mnschoonmaker** [comment]
I don't know how to GitHub but I'll try

Mike Schoonmaker
Sent from my iPhone
Please excuse any spelling errors

On Oct 26, 2022, at 4:45 PM, 9swampy ***@***.***> wrote:

﻿

Not sure where the zip went; any chance you could commit to a fork of the repo and I'll pick it up and take a look?

**Comment by mnschoonmaker** [comment]
How does one "commit to a fork"?

**Comment by mnschoonmaker** [comment]
[400 - Copy.zip](https://github.com/9swampy/DeepNestSharp/files/9874486/400.-.Copy.zip)
attaching the zip file here

**Comment by 9swampy** [comment]
That zip only has your dxfs; I was hoping to get your dnproj too; that would have (most) of the settings you're trying to use which would help.

Regardless I set up a new project with a single 100x100 sheet and loaded 3x1.dxf (from the Dxfs folder in the application folder).
Each 1.dxf is 50x50; with SheetSpacing=0 and Spacing=0 then all 3 fit onto the 100x100 sheet.

![image](https://user-images.githubusercontent.com/523054/198911412-083e3da9-4ccd-4c40-9a8d-d755d14bda46.png)

With SheetSpacing=10 the sheet is reduced accordingly and only 1 part fits on each sheet:
![image](https://user-images.githubusercontent.com/523054/198911682-0eafede6-1431-4294-9c34-9247956bc202.png)

Bumping the sheet up to 150x100 two now fit horizontally (and there's no space between the two parts), but still only 1 vertically:
![image](https://user-images.githubusercontent.com/523054/198911807-6208242e-4fe4-49c4-8a97-a3f968aa99d4.png)

Dropping SheetSpacing=0 and bumping Spacing=10 still get 2 parts horizontally, only 1 vertically:
![image](https://user-images.githubusercontent.com/523054/198911975-72f270f3-c800-436f-ab8e-caa6ee1febb5.png)
Note the holes are smaller too; that's because the code is working by adding to the size of the parts; but that's only internal to the application.

![image](https://user-images.githubusercontent.com/523054/198912089-a0fd7295-1363-4cec-9ce5-7fe2d40b638e.png)
If you 
1. pop out the NestResult and then 
2. pop out the SheetPlacement and then
3. LoadAllExact you'll see:
![image](https://user-images.githubusercontent.com/523054/198912197-fc87b8c1-153b-43a1-abae-16a938e095a0.png)

The two parts are horizontally spaced and that's what you'd get upon export.

I do admit this isn't a great UX... but it's all inherited from the original coding and I've just not paid it much attention. See if that helps you out; I was getting similar results using your Dxfs...
![image](https://user-images.githubusercontent.com/523054/198912650-b11b3ca6-3a26-4b72-a083-5c7c76cbcbb0.png)
![image](https://user-images.githubusercontent.com/523054/198912532-78c1b25e-b86f-48e6-9959-38a0966b2200.png)
![image](https://user-images.githubusercontent.com/523054/198912682-2f6a4694-6cf9-4b58-9f43-ce9f3f2e3af5.png)

**Comment by mnschoonmaker** [comment]
Attaching my project (*.dnest) as well.
[Ratrig Panel Nesting.zip](https://github.com/9swampy/DeepNestSharp/files/9902364/Ratrig.Panel.Nesting.zip)

**Comment by 9swampy** [comment]
Didn't change any settings; loaded your project and relinked the parts files and ran it:

![image](https://user-images.githubusercontent.com/523054/199617585-3016d249-1af2-4f0f-a717-719fcf52886b.png)

Which exports/LoadAllExact gives
![image](https://user-images.githubusercontent.com/523054/199617715-e756e558-c0a2-4848-8c8f-7ab7efa484b6.png)

As a side note, there may be something going wrong with your scaling because the parts were tiny compared to the size of your sheet (which I reduced to 300x50 for the purposes of taking the screenshots above); but the spacing works correctly as shown above. Aren't you getting the same?

**Comment by 9swampy** [comment]
Mike, how did this work out for you?

**Comment by mnschoonmaker** [comment]
THANK YOU for following up! This forced me to take another look. I found 2 things:
1. (based upon your note re: sizing), I changed my dxf parts to use their metric counterparts. This explains your sizing concerns.
2. The lack of spacing that I brought up was based upon viewing the layouts in the app itself - NOT the dxf exports! When I (re)ran this with metric parts, I observed NO spacing in the app sheet layouts, but when I actually exported the dxf layout, the spacing was present! Not sure if this is the expected behavior or "by design", but it was kind of non-intuitive to not see the spacing while in the app preview.

Thanks!

**Comment by 9swampy** [comment]
Glad it worked out for you.

1.  Nice, makes sense.
2.  It's a consequence of what I started with and tbh I hadn't noticed because I always work with a zero kerf. The LoadAllExact I only put in to fix the previews which show the approximations actually nested by default so I could make sense of why the nest resulted as it did. It's making sense now but some crazy stuff was happening with early incarnations... so it was just an unintended side effect of that which clearly confused you; sorry for that but glad the explanation has helped.
