### ISSUE TITLE
Error when importing dxf

### ISSUE THREAD

**Issue by FlorianSan** [9swampy/DeepNestSharp#15]
Hi, 
I have a problem importing a set of dxf, I don't understand why? 
![Capture d'écran 2023-03-30 171925](https://user-images.githubusercontent.com/17226527/228884335-1d413054-335e-44c9-ad8c-9a77e4ca47c6.png)

What is the procedure to know the elements that cause problems?

Thanks
[marche_acier.zip](https://github.com/9swampy/DeepNestSharp/files/11113194/marche_acier.zip)

**Comment by 9swampy** [comment]
Yeah, it's not exactly helpful here. Problem invariably is because your objects aren't properly closed. Opening the first couple (using https://sharecad.org/viewer) you have included numbers in the middle of your parts; that's not going to be a valid closed shape.

![image](https://github.com/9swampy/DeepNestSharp/assets/523054/9ca15127-cd74-4f7b-9a5f-14f71cc09fa2)

**Comment by FlorianSan** [comment]
Yes, I understand completely, but the number in the centre and the lines that make the shape not closed are on another layer. Would it be possible to nest only on a layer that is a closed part and apply the other layers afterwards?

**Comment by groyk** [comment]
I think that would be a great idea. We also hava parts with engraved bending lines, naming, charge numbers ect.

If cut layer could be set, and all other layers is just passed "as is". it would be a great feature

**Comment by 9swampy** [comment]
Make the numbers a valid shape (with some volume). You have to highlight them anyhow to engraver instead of cut, no?
